services:
  # Finance Agent
  finance:
    build:
      context: ./Finance
    container_name: finance_agent
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - FINANCE_MODEL=${FINANCE_MODEL}
      - API_KEY=${API_KEY}
      - LITELLM_API_KEY=${LITELLM_API_KEY}
      - FINANCE_MCP_SERVER_URL=${FINANCE_MCP_SERVER_URL}
    ports:
      - "2024:2024"
    networks:
      - agent_network
    restart: unless-stopped

  # Inventory Agent
  inventory:
    build:
      context: ./Inventory
    container_name: inventory_agent
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - INVENTORY_MODEL=${INVENTORY_MODEL}
      - CHROMA_PERSIST_DIR=/app/chroma_data
      - API_KEY=${API_KEY}   
      - LITELLM_API_KEY=${LITELLM_API_KEY}
      - INVENTORY_MCP_SERVER_URL=${INVENTORY_MCP_SERVER_URL}
    ports:
      - "2025:2025"
    networks:
      - agent_network
    restart: unless-stopped

  # Sales Agent
  sales:
    build:
      context: ./Sales
    container_name: sales_agent
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - SALES_MODEL=${SALES_MODEL}
      - VISION_MODEL=${VISION_MODEL}
      - INVENTORY_A2A_AID=${INVENTORY_A2A_AID}
      - FINANCE_A2A_AID=${FINANCE_A2A_AID}
      - API_KEY=${API_KEY}
      - LITELLM_BASE_URL=${LITELLM_BASE_URL}
      - LITELLM_API_KEY=${LITELLM_API_KEY}
      - ROOT_AGENT_IDENTIFIER=${ROOT_AGENT_IDENTIFIER}
    ports:
      - "2026:2026"
    networks:
      - agent_network
    restart: unless-stopped

 # Ollama Server
  ollama:
    build:
      context: ./Ollama
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - "11434:11434"
    networks:
      - agent_network
    restart: unless-stopped

networks:
  agent_network:
    driver: bridge
